### ISSUE TITLE
Take the first remote with a `ssh://` push URL

### ISSUE THREAD

**Issue by RaitoBezarius** [9999years/git-gr#38]
To avoid having to set a `gerrit` remote or have a push URL with `gerrit` in the URL.

**Comment by 9999years** [comment]
The first remote with what ordering? Alphabetically?

**Comment by 9999years** [comment]
I probably want to have some explicit configuration options like this tool...

https://github.com/shanesmith/gerrit-cli/blob/46295266d18b01f59ce7d2c87df6f7429c45bb17/lib/gerrit.js#L59-L74

**Comment by RaitoBezarius** [comment]
Yeah alphabetically sounds good

Le ven. 5 avr. 2024, 20:35, Rebecca Turner ***@***.***> a
écrit :
